name = "trigger-command"
description = "A Spin trigger that executes the WASI main function of a component."
version = "0.2"
spin_compatibility = ">=2.0"
license = "Apache-2.0"
package = "./target/release/trigger-command"
